### PR TITLE
Fatarrowfuncs

### PR DESCRIPTION
**Pull request by sliceking**
added fat arrow functions and let where applicable. issue #6

### CODE REVIEW

**Comment by bhavyaagg** [comment]
Hey @svwielga4 . Merge conflicts here also. Please resolve.

**Comment by svwielga4** [comment]
I cleaned it up! Thanks for letting me know = )

**Comment by svwielga4** [comment]
This also solves #5

**Review by bhavyaagg — CHANGES_REQUESTED** [review]
Please see the changes.

**Comment by svwielga4** [comment]
requested changes added = )

**Review by bhavyaagg — APPROVED** [review]

**Pull request merged**
